Split user manual in chapter files
project-chip/certification-tool pull request #177
Opened 2024-02-07 18:21 UTC by hiltonlima

2024-02-07 18:56 UTC, rquidute reviewed
Could you please update the year in the copyright text to `2024`?

2024-02-09 12:16 UTC, rquidute approved these changes

2024-02-09 13:22 UTC, antonio-amjr commented on docs/Matter_TH_User_Guide/11-TestCaseExecution.adoc
> +Refer to <<references, Section 2, References>> for PICS tool documentation to generate the PICS XML files.
Is `References` still section 2?

2024-02-09 13:23 UTC, antonio-amjr commented on docs/Matter_TH_User_Guide/3-TableOfContents.adoc
> +toc::[]
Table of content is not showing nothing

2024-02-09 13:27 UTC, antonio-amjr commented on docs/Matter_TH_User_Guide/11-TestCaseExecution.adoc
> +Refer to <<references, Section 2, References>> for PICS tool documentation to generate the PICS XML files.
Review all other asciidoc references as well

2024-02-09 13:53 UTC, antonio-amjr requested changes
Take a look in the comments above and solve the conflicts of this PR

2024-02-15 17:44 UTC, antonio-amjr commented on docs/Matter_TH_User_Guide/11-TestCaseExecution.adoc
> +Refer to <<references, Section 2, References>> for PICS tool documentation to generate the PICS XML files.
The reference seems ok for the whole document. No issue there

2024-02-15 17:46 UTC, antonio-amjr commented on docs/Matter_TH_User_Guide/3-TableOfContents.adoc
> +toc::[]
The Table of Content shows the information for the whole document.

2024-02-15 17:46 UTC, antonio-amjr approved these changes

2024-02-15 19:05 UTC, merged