Remove lib version
project-chip/certification-tool pull request #203
Opened 2024-02-27 18:02 UTC by hiltonlima

Fix installation issue:

![image](https://github.com/project-chip/certification-tool/assets/116589806/94e173a0-3410-4338-b2b7-8651c6d10514)

2024-02-27 18:18 UTC, fabiowmm requested changes
Can you better explain the motivation/rational for this change?

2024-02-28 15:18 UTC, hiltonlima commented on scripts/ubuntu/1-install-dependendcies.sh
> +    "libssl-dev (>=3.0.2-0ubuntu1.14)"               # Apparently with each update, previous versions of the library are removed
Greater than or equal to: 3.0.2-0ubuntu1.14

2024-02-28 15:18 UTC, hiltonlima commented on scripts/ubuntu/1-install-dependendcies.sh
> +    "avahi-utils (>=0.8-5ubuntu5.2)"                 # Matter uses Avahi
Greater than or equal to: 0.8-5ubuntu5.2

2024-02-28 15:19 UTC, hiltonlima commented on scripts/ubuntu/1-install-dependendcies.sh
> +    "unzip (>=6.0-26ubuntu3.1)"
Greater than or equal to: 6.0-26ubuntu3.1

2024-02-28 15:23 UTC, hiltonlima commented on scripts/ubuntu/1-install-dependendcies.sh
> +IFS=$SAVEIFS
If we want to call 1 time once... We need a command like this:  `apt satisfy 'package1 (>=34.1)', package2 (=1.1)`

Packages must be separated by commas

2024-02-28 15:46 UTC, rquidute approved these changes

2024-02-28 17:05 UTC, antonio-amjr approved these changes

2024-02-28 19:50 UTC, fabiowmm approved these changes

2024-02-28 20:06 UTC, merged